#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
picom -b --backend xrender &
redshift -l 0:0 6000:3600 &
telegram &
copyq &
polybar &
flameshot &
feh --bg-fill $HOME/Pictures/desktop/space_body.png &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#000000"
#bspc config normal_border_color  "#363636"
bspc config normal_border_color  "#A2FFFF"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a copyq state=floating
